export const GITLAB_API_BASE_URL = process.env.REACT_APP_GITLAB_API_BASE_URL;
export const GITLAB_API_VERSION_URL = process.env.REACT_APP_GITLAB_API_VERSION_URL;
export const GITLAB_API_APP_ID = process.env.REACT_APP_GITLAB_API_APP_ID;
export const GITLAB_API_APP_SECRET = process.env.REACT_APP_GITLAB_API_APP_SECRET;
export const GITLAB_REDIRECT_URL = process.env.REACT_APP_GITLAB_REDIRECT_URL;
export const GITLAB_GET_AUTH_CODE_URL = process.env.REACT_APP_GITLAB_GET_AUTH_CODE_URL;
